[package]
name = "hn-decypher"
authors = ["generic-user1"]
description = "Decrypts the \"dec\" file format from the video game Hacknet without needing any password"
license = "MIT"
readme = "README.md"
repository = "https://github.com/generic-user1/hn-decypher"
categories = ["command-line-utilities", "games"]
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
roxmltree = { version = "0.21.1", optional = true }
thiserror = "2.0.20"

[features]
default = ["save_read"]
save_read = ["dep:roxmltree"]
